from typing import Protocol, List, Optional

class ScraperProtocol(Protocol):
    def open_home(self) -> None: ...
    def collect_video_links(self, seed_url: Optional[str], scrolls: int = 8) -> List[str]: ...
    def shutdown(self) -> None: ...
