<?php

declare(strict_types=1);

return [
    'fallback_locale' => 'en',

    'en' => [
        'errors' => [
            'action_not_allowed' => 'Action ":action" is not allowed.',
            'task_not_found' => 'Task not found.',
            'blocked_task_missing_resume_token' => 'This blocked task is missing a valid resume token.',
            'command_failed' => 'The Telegram command could not be completed.',
            'unknown_command' => 'Unknown command: :command',
            'unsupported_action_payload' => 'Unsupported Telegram action payload.',
            'code_summary_required' => 'A task summary is required for /code.',
            'issue_key_required' => 'Issue key is required. Use /issue OPAS-0069 [optional summary].',
            'resume_usage_required' => 'Use /resume <task-id> <response> to continue a blocked task.',
            'bot_token_missing' => 'Telegram bot token is not configured.',
            'empty_response_payload' => 'Telegram returned an empty response payload.',
            'request_failed' => 'Telegram request failed.',
            'issue_context_selection_invalid' => 'Choose one of the suggested source task ids before continuing.',
        ],
        'callbacks' => [
            'chat_start' => 'Starting chat mode...',
            'chat_status' => 'Loading chat session...',
            'chat_stop' => 'Stopping chat mode...',
            'chat_reset' => 'Resetting chat session...',
            'menu' => 'Opening menu...',
            'create_task' => 'Creating task...',
            'status' => 'Loading status...',
            'next_action' => 'Loading next action...',
            'follow_up' => 'Loading follow-up...',
            'validation' => 'Loading validation...',
            'github_status' => 'Loading GitHub status...',
            'summary' => 'Loading summary...',
            'changes' => 'Loading changes...',
            'queue' => 'Loading queue...',
            'cancel_task' => 'Cancelling task...',
            'cancel_tasks' => 'Cancelling active tasks...',
            'delete_task' => 'Deleting pending task...',
            'delete_tasks' => 'Deleting pending tasks...',
            'reset' => 'Cleaning chat...',
            'resume' => 'Resuming task...',
            'default' => 'Working...',
        ],
        'bot_commands' => [
            'start' => 'Start direct Codex chat mode',
            'chat_start' => 'Start direct Codex chat mode',
            'chat_status' => 'Show direct chat session status',
            'stop' => 'Stop direct chat mode',
            'chat_stop' => 'Stop direct chat mode',
            'chat_reset' => 'Reset direct chat context',
            'chat_mode' => 'Show or switch direct chat mode',
            'code' => 'Create a remote coding task',
            'issue' => 'Create a coding task from one issue key',
            'review' => 'Create a remote review task',
            'validate' => 'Create a remote validation task',
            'status' => 'Show task status',
            'next_action' => 'Show the next action',
            'follow_up' => 'Show follow-up details',
            'validation_report' => 'Show validation results',
            'github' => 'Show GitHub context for one task',
            'summary' => 'Show latest task summary',
            'changes' => 'Show changed files',
            'queue' => 'Show latest task queue',
            'clear' => 'Clear this chat session',
            'clear_all' => 'Clear all tracked bot messages',
            'cancel' => 'Cancel one task',
            'cancel_all' => 'Cancel all active tasks',
            'delete' => 'Delete one pending task',
            'delete_all' => 'Delete all pending tasks or use /delete_all --force to clear DB',
            'reset' => 'Clear recent bot messages',
            'resume' => 'Resume a blocked task',
            'help' => 'Show remote control help',
        ],
        'buttons' => [
            'code' => 'Code',
            'guide' => 'Guide',
            'create_menu' => 'Create',
            'reports_menu' => 'Reports',
            'maintenance_menu' => 'Maintenance',
            'back_home' => 'Back Home',
            'code_examples' => 'Code Examples',
            'task_templates' => 'Task Templates',
            'template_bugfix' => 'Bugfix',
            'template_refactor' => 'Refactor',
            'template_review' => 'Review Template',
            'template_validate' => 'Validate Template',
            'latest_blocked' => 'Latest Blocked',
            'latest_failed' => 'Latest Failed',
            'latest_running' => 'Latest Running',
            'resume_latest_blocked' => 'Resume Latest Blocked',
            'next_action' => 'Next Action',
            'follow_up' => 'Follow-up',
            'validation' => 'Validation',
            'github' => 'GitHub',
            'cancel_task' => 'Cancel Task',
            'cancel_latest_running' => 'Cancel Latest Running',
            'cancel_all_active' => 'Cancel All Active',
            'delete_task' => 'Delete Queue',
            'delete_all_pending' => 'Delete All Queue',
            'delete_all_tasks' => 'Delete All Tasks',
            'latest_status' => 'Latest Status',
            'latest_summary' => 'Latest Summary',
            'latest_changes' => 'Latest Changes',
            'latest_github' => 'Latest GitHub',
            'queue' => 'Queue',
            'chat_start' => 'Chat with Codex',
            'chat_status' => 'Chat Status',
            'chat_stop' => 'Exit Codex',
            'chat_reset' => 'Reset Chat Mode',
            'clear_chat' => 'Clear Chat',
            'clear_all_chat' => 'Clear All Chat',
            'reset' => 'Clear Chat',
            'status' => 'Status',
            'summary' => 'Summary',
            'changes' => 'Changes',
            'review' => 'Start Review',
            'validate' => 'Run Validate',
            'pending' => 'Pending',
            'running' => 'Running',
            'blocked' => 'Blocked',
            'failed' => 'Failed',
            'completed' => 'Completed',
            'cancelled' => 'Cancelled',
            'resume' => 'Resume',
            'confirm_yes' => 'Yes',
            'confirm_no' => 'No',
        ],
        'labels' => [
            'clarify_request' => 'Clarify request',
            'confirm_action' => 'Confirm action',
            'original_message' => 'Original message',
            'action' => 'Action',
            'target' => 'Target',
            'commands' => 'Commands',
            'chat_session' => 'Chat session',
            'chat_mode' => 'Chat mode',
            'session_id' => 'Session id',
            'started_at' => 'Started at',
            'last_message' => 'Last message',
            'recent_activity' => 'Recent activity',
            'activity_snapshot' => 'Activity snapshot',
            'needs_attention' => 'Needs attention',
            'current_tasks' => 'Current tasks',
            'task' => 'Task',
            'tasks' => 'Tasks',
            'summary' => 'Summary',
            'message' => 'Message',
            'status' => 'Status',
            'repository' => 'Repository',
            'validation' => 'Validation',
            'validate' => 'Validate',
            'run' => 'Run',
            'machine' => 'Machine',
            'provider' => 'Provider',
            'phase' => 'Phase',
            'focus' => 'Focus',
            'worker' => 'Worker',
            'host' => 'Host',
            'issue' => 'Issue',
            'source_task' => 'Source task',
            'next_action' => 'Next action',
            'follow_up' => 'Follow-up',
            'reason' => 'Reason',
            'guidance' => 'Guidance',
            'workspace_policy' => 'Workspace policy',
            'input_type' => 'Input type',
            'question' => 'question',
            'total_commands' => 'Total commands',
            'failed_commands' => 'Failed commands',
            'branch' => 'Branch',
            'compare' => 'Compare',
            'pull_request' => 'Pull request',
            'pr_note' => 'PR note',
            'ci' => 'CI',
            'ci_note' => 'CI note',
            'last_seen' => 'Last seen',
            'configured' => 'Configured',
            'url' => 'URL',
            'pending_updates' => 'Pending updates',
            'last_error' => 'Last error',
            'scope' => 'Scope',
            'deleted_tasks' => 'Deleted tasks',
            'changed_files' => 'Changed files',
            'failure' => 'Failure',
            'details' => 'Details',
            'headline' => 'Headline',
            'queued_task' => 'Queued task',
            'running_task' => 'Running task',
            'validation_for_task' => 'Validation for task',
            'github_for_task' => 'GitHub for task',
            'blockers' => 'Blockers',
            'bulk_cancellation_completed' => 'Bulk cancellation completed.',
            'deleted_pending_task' => 'Deleted pending task',
            'bulk_pending_deletion_completed' => 'Bulk pending-task deletion completed.',
            'changed_files_for_task' => 'Changed files for task',
            'resume_accepted_for_task' => 'Resume accepted for task',
            'command_sync' => 'Telegram command sync',
            'workflow_steps' => 'Workflow steps',
            'task_update' => 'Task update',
            'cancelled_immediately' => 'Cancelled immediately',
            'cancellation_requested_running' => 'Cancellation requested (running)',
            'unchanged' => 'Unchanged',
            'create_tasks' => 'Create Tasks',
            'coding_task_examples' => 'Coding Task Examples',
            'task_templates' => 'Task Templates',
            'bugfix_template' => 'Bugfix Template',
            'refactor_template' => 'Refactor Template',
            'review_template' => 'Review Template',
            'validation_template' => 'Validation Template',
            'reports' => 'Reports',
            'maintenance' => 'Maintenance',
            'queue_management' => 'Queue Management',
            'recommended_next_actions' => 'Recommended next actions:',
            'example_prompts' => 'Example prompts:',
            'home_dashboard' => 'Home dashboard',
            'quick_start' => 'Quick start',
            'chat_session_started' => 'Chat session started',
            'chat_session_stopped' => 'Chat session stopped',
            'chat_session_reset' => 'Chat session reset',
        ],
        'values' => [
            'yes' => 'yes',
            'no' => 'no',
            'unknown' => 'unknown',
            'online' => 'online',
            'stale' => 'stale',
            'pending' => 'pending',
            'running' => 'running',
            'completed' => 'completed',
            'failed' => 'failed',
            'blocked' => 'blocked',
            'cancelled' => 'cancelled',
            'skipped' => 'skipped',
            'active' => 'active',
            'inactive' => 'inactive',
            'all' => 'all',
            'terminal' => 'terminal',
        ],
        'help' => [
            'title' => 'OPAS remote coding control',
            'no_worker_reported' => 'No worker has reported yet.',
            'quick_start_steps' => [
                '1. Use /start when you want Telegram to behave like the remote Codex control chat.',
                '2. Send a normal message for Codex to answer. Use clear coding verbs when you want code changed.',
                '3. Use /queue to inspect, stop, or clean pending work.',
                '4. Use /changes latest to inspect changed files, or /clear when the session is no longer needed.',
            ],
            'commands' => [
                '/start - start direct Codex chat mode on the connected machine',
                '/chat_status - show the current direct chat session state',
                '/stop - stop direct Codex chat mode',
                '/chat_reset - clear the current direct chat context and start fresh',
                '/changes [task-id|latest] - show changed files',
                '/queue [pending|running|blocked|failed|completed] - show task queue',
                '/cancel [task-id|latest:running] - cancel one task',
                '/cancel_all - cancel active queued work',
                '/delete [task-id|latest:pending] - delete one pending queued task',
                '/delete_all - delete pending queued tasks',
                '/clear [--force] - clear tracked bot messages for the current chat session',
                '/clear_all [--force] - clear all tracked bot messages from oldest to newest',
            ],
            'buttons_hint' => 'Use the buttons below for chat mode, queue management, changed files, and chat cleanup.',
            'no_active_tasks' => 'No local auto-coding task is active right now.',
            'tip' => 'Tip: if you are new, start with /queue, then /status latest, then /summary latest.',
        ],
        'menus' => [
            'create' => [
                'Use this menu when you want to start coding or review work remotely.',
                'Buttons can start quick review and validation tasks immediately.',
                'For coding tasks, send a summary such as: /code Refactor Telegram task menu',
                'You can add details with flags like --issue, --scope, --path, --provider, and --model.',
            ],
            'create_code' => [
                'Use /code when you want the connected machine to implement or refactor code.',
                'Useful flags: --issue, --scope, --path, --provider, --model, --validate, --no-validate',
            ],
            'create_templates' => [
                'Use these templates when you want a safer starting point than writing a prompt from scratch.',
                'Choose a bugfix, refactor, review, or validation template below and copy the matching command.',
            ],
            'template_bugfix' => [
                'Use this when something is broken and you want the machine to focus on diagnosis, fix, and verification.',
                'Add --scope when you already know the affected files or folders.',
            ],
            'template_refactor' => [
                'Use this when behavior should stay stable but structure, readability, or duplication should improve.',
                'Prefer a focused --scope for refactors so the machine stays inside the intended boundary.',
            ],
            'template_review' => [
                'Use this when you want a review-style pass that looks for defects, regressions, and missing validation.',
                'Pair review with /summary latest or /changes latest after the machine finishes.',
            ],
            'template_validate' => [
                'Use this when you mainly want lint, static analysis, tests, or other configured checks to run remotely.',
                'Use /validation_report latest later to inspect the results in a compact format.',
            ],
            'reports' => [
                'Use this menu to inspect what the connected machine has done.',
                'Latest Status shows the newest task state.',
                'Latest Summary shows the execution outcome, validation, and next action.',
                'Latest Changes lists changed files from the latest run.',
                'GitHub shows the current issue key, repository slug, compare URL, and any available PR or CI status.',
                'Queue shows the recent pending, running, blocked, failed, or completed tasks.',
                'Use Pending, Running, Blocked, Failed, or Completed filters when you want one workflow slice only.',
            ],
            'maintenance' => [
                'Use this menu for chat cleanup and quick navigation.',
                'Reset Chat removes recent bot messages that were tracked in this chat.',
                'Guide returns to the main onboarding screen.',
                'Queue and Latest Status are included here for quick recovery when the chat becomes noisy.',
                'Sync Commands refreshes the Telegram command list when the bot menu changes.',
                'Use cancel actions to stop one task or all active tasks before creating a new request.',
                'Use purge when you want to remove old terminal tasks from history completely.',
            ],
            'queue' => [
                'Use this menu to inspect queued, running, and blocked work.',
                'Stop the latest running task when Codex is busy with the wrong request.',
                'Delete pending work when a queued message is no longer needed.',
            ],
        ],
        'phrases' => [
            'provide_value' => 'Provide a value.',
            'no_next_action_recorded' => 'No explicit next action is recorded yet.',
            'no_follow_up_required' => 'No follow-up input is currently required.',
            'no_validation_run' => 'has no validation run yet.',
            'no_recorded_changed_files' => 'has no recorded changed files.',
            'more_files' => '+:count more files',
            'no_execution_run' => 'has no execution run yet.',
            'resume_workflow_continue' => 'The connected machine will continue the workflow.',
            'task_removed_permanently' => 'The task was removed from the database permanently.',
            'no_worker_machine_reported' => 'No auto-coding worker machine has reported yet.',
            'no_tasks_for_status_filter' => 'No :status auto-coding tasks found.',
            'no_local_tasks' => 'No local auto-coding tasks found.',
            'latest_tasks_for_status_filter' => 'Latest :status auto-coding tasks',
            'latest_tasks' => 'Latest auto-coding tasks',
            'task_without_changed_files' => 'Task #:task_id has no recorded changed files.',
            'resume_format' => 'Resume format: /resume :task_id :question_pairs',
            'chat_cleaned' => 'Chat cleaned. Use /start or the buttons below to continue.',
            'chat_cleaned_force' => 'Chat cleaned. Force cleanup was requested; Telegram deleted additional messages where permissions allowed.',
            'chat_cleaned_all' => 'All tracked bot messages were cleared from oldest to newest. Use /start to continue.',
            'chat_cleaned_all_force' => 'All tracked bot messages were cleared from oldest to newest. Force cleanup also tried to delete your trigger message where permissions allowed.',
            'changed_file_added' => 'Added during the latest run.',
            'changed_file_deleted' => 'Deleted during the latest run.',
            'changed_file_renamed' => 'Renamed or moved during the latest run.',
            'changed_file_modified' => 'Modified during the latest run.',
            'changed_file_touched' => 'Touched during the latest run; no detailed per-file summary was recorded.',
            'chat_session_started' => 'Direct chat mode is active. Send normal messages for Codex to answer from the connected machine.',
            'chat_session_connected' => 'Connected to Codex.',
            'chat_session_inactive' => 'Direct chat mode is currently off for this Telegram chat.',
            'chat_session_start_hint' => 'Use /start when you want Telegram messages to act like a remote Codex session.',
            'chat_ping_received' => 'Telegram bot received your message.',
            'chat_ping_no_task_created' => 'This was treated as a connection check, so no Codex coding task was created. Send a concrete coding request when you want Codex to work.',
            'chat_session_reset' => 'Direct chat context was reset. The next message starts a fresh remote coding thread.',
            'chat_session_stopped' => 'Direct chat mode is off. Slash commands and task reports still work normally.',
            'chat_session_hint' => 'While chat mode is active, plain text is answered by Codex. Concrete coding requests still create queued work on the connected machine.',
            'direct_chat_queued' => 'Codex is preparing a reply...',
            'direct_chat_running' => 'Codex is replying...',
            'direct_chat_failed' => 'Codex could not reply.',
            'direct_chat_empty' => 'Codex finished without a text reply.',
            'media_message_needs_caption' => 'Image received. Send it again with a short caption describing what to change, or type the request as text.',
            'chat_session_no_active_task' => 'No active task is linked to this chat session yet.',
            'chat_session_no_recent_activity' => 'No recent chat-session activity has been recorded yet.',
            'task_has_no_execution_run' => 'Task #:task_id has no execution run yet.',
            'task_has_no_validation_run' => 'Task #:task_id has no validation run yet.',
            'task_has_no_follow_up' => 'Task #:task_id has no follow-up input requirement.',
            'ci_failed_check_ratio' => ':failed/:total failed checks',
            'validation_failed_command_ratio' => ':failed/:total validation commands failed',
            'github_headline_ci_attention' => 'CI needs attention before merge.',
            'github_headline_pr_open_ci_passing' => 'PR is open and CI is passing.',
            'github_headline_pr_closed' => 'Pull request workflow is already closed.',
            'github_headline_compare_ready' => 'Branch compare link is ready for GitHub follow-up.',
            'github_headline_local_fallback' => 'GitHub context is available with local fallback only.',
            'github_blocker_compare_unavailable' => 'Compare URL is unavailable for the current branch.',
            'github_blocker_pr_unavailable' => 'Pull request status is not connected yet; inspect GitHub manually or configure integration.',
            'github_blocker_ci_unavailable' => 'CI status is unavailable from local GitHub context.',
            'github_blocker_ci_failed_default' => 'CI checks are not passing.',
            'github_next_action_fix_ci' => 'Resolve the failing CI checks before merge.',
            'github_next_action_open_compare_pr' => 'Open the compare URL to create or inspect the pull request.',
            'github_next_action_review_merge_pr' => 'Review the current pull request and merge when ready.',
            'github_next_action_no_follow_up' => 'No immediate GitHub follow-up is required.',
            'github_next_action_manual_follow_up' => 'Review the compare URL and continue GitHub follow-up manually.',
            'queued_reused_issue_context' => 'Reused issue context from task #:task_id.',
            'queued_scope_path_count' => ':count path(s)',
            'cancel_requested' => 'Cancellation was requested. The worker will stop this run at the next safe checkpoint.',
            'cancelled_removed_from_active' => 'Task was cancelled and removed from active execution.',
            'pending_interaction_cancelled' => 'Confirmation cancelled.',
            'workflow_step_inspect_repository' => 'Inspect repository',
            'workflow_step_prepare_prompt' => 'Prepare prompt',
            'workflow_step_provider_plan' => 'Provider execution',
            'workflow_step_collect_github_context' => 'Collect GitHub context',
            'workflow_step_run_validation' => 'Run validation',
            'workflow_step_completion_check' => 'Completion check',
            'workflow_phase_execution_started' => 'Execution started',
            'workflow_focus_execution_started' => 'The connected machine has claimed the task and is beginning remote execution.',
            'workflow_focus_in_progress' => 'The connected machine is still working through the current phase.',
            'workflow_focus_blocked' => 'The workflow is waiting for operator input before it can continue.',
            'workflow_focus_completed' => 'The latest workflow phase has completed.',
            'workflow_focus_failure' => 'The workflow stopped because one execution phase failed.',
            'chat_timeline_queued' => 'Queued task #:task_id.',
            'chat_timeline_running' => 'Running task #:task_id.',
            'chat_timeline_completed' => 'Completed task #:task_id.',
            'chat_timeline_failed' => 'Failed task #:task_id.',
            'chat_timeline_blocked' => 'Blocked task #:task_id.',
            'chat_timeline_cancelled' => 'Cancelled task #:task_id.',
            'clarify_request_prompt' => 'Your message is ambiguous. Choose what you want to do next.',
            'issue_context_clarify_prompt' => 'I found multiple previous :task_type task contexts for issue :issue_key. Choose which one to reuse.',
            'issue_context_reply_hint' => 'Reply with one source task id or choose a button below.',
            'confirm_action_prompt' => 'Please confirm this action before it runs.',
            'no_pending_clarification' => 'No pending clarification is active now. Send the request again.',
            'no_pending_issue_context_clarification' => 'No pending issue-context choice is active now. Send the request again.',
            'no_pending_confirmation' => 'No pending confirmation is active now. Send the request again.',
        ],
    ],
    'vi' => [
        'errors' => [
            'action_not_allowed' => 'Hành động ":action" không được phép.',
            'task_not_found' => 'Không tìm thấy task.',
            'blocked_task_missing_resume_token' => 'Task đang bị chặn này không có resume token hợp lệ.',
            'command_failed' => 'Không thể hoàn thành lệnh Telegram này.',
            'unknown_command' => 'Lệnh không hỗ trợ: :command',
            'unsupported_action_payload' => 'Payload thao tác Telegram không được hỗ trợ.',
            'code_summary_required' => 'Lệnh /code cần có mô tả task.',
            'issue_key_required' => 'Cần có issue key. Dùng /issue OPAS-0069 [mô tả tùy chọn].',
            'resume_usage_required' => 'Dùng /resume <task-id> <response> để tiếp tục task đang bị chặn.',
            'bot_token_missing' => 'Chưa cấu hình Telegram bot token.',
            'empty_response_payload' => 'Telegram trả về payload rỗng.',
            'request_failed' => 'Gọi Telegram thất bại.',
            'issue_context_selection_invalid' => 'Hãy chọn một source task id trong các gợi ý trước khi tiếp tục.',
        ],
        'callbacks' => [
            'chat_start' => 'Đang bật chat mode...',
            'chat_status' => 'Đang tải chat session...',
            'chat_stop' => 'Đang tắt chat mode...',
            'chat_reset' => 'Đang reset chat session...',
            'menu' => 'Đang mở menu...',
            'create_task' => 'Đang tạo task...',
            'status' => 'Đang tải trạng thái...',
            'next_action' => 'Đang tải bước tiếp theo...',
            'follow_up' => 'Đang tải follow-up...',
            'validation' => 'Đang tải validation...',
            'github_status' => 'Đang tải trạng thái GitHub...',
            'summary' => 'Đang tải tóm tắt...',
            'changes' => 'Đang tải thay đổi...',
            'queue' => 'Đang tải hàng chờ...',
            'cancel_task' => 'Đang hủy task...',
            'cancel_tasks' => 'Đang hủy các task đang hoạt động...',
            'delete_task' => 'Đang xóa hẳn task pending...',
            'delete_tasks' => 'Đang xóa hẳn các task pending...',
            'reset' => 'Đang dọn chat...',
            'resume' => 'Đang tiếp tục task...',
            'default' => 'Đang xử lý...',
        ],
        'bot_commands' => [
            'start' => 'Bật chat Codex trực tiếp',
            'chat_start' => 'Bật chat Codex trực tiếp',
            'chat_status' => 'Xem trạng thái chat session trực tiếp',
            'stop' => 'Tắt chat Codex trực tiếp',
            'chat_stop' => 'Tắt chat Codex trực tiếp',
            'chat_reset' => 'Reset context chat trực tiếp',
            'chat_mode' => 'Xem hoặc đổi direct chat mode',
            'code' => 'Tạo task coding từ xa',
            'issue' => 'Tạo task coding từ một issue key',
            'review' => 'Tạo task review từ xa',
            'validate' => 'Tạo task validation từ xa',
            'status' => 'Xem trạng thái task',
            'next_action' => 'Xem bước tiếp theo',
            'follow_up' => 'Xem chi tiết follow-up',
            'validation_report' => 'Xem kết quả validation',
            'github' => 'Xem context GitHub của một task',
            'summary' => 'Xem tóm tắt task mới nhất',
            'changes' => 'Xem file thay đổi',
            'queue' => 'Xem hàng chờ task mới nhất',
            'clear' => 'Dọn chat session hiện tại',
            'clear_all' => 'Dọn toàn bộ message bot đã track',
            'cancel' => 'Hủy một task',
            'cancel_all' => 'Hủy toàn bộ task active',
            'delete' => 'Xóa hẳn một task pending',
            'delete_all' => 'Xóa toàn bộ pending hoặc dùng /delete_all --force để clear DB',
            'reset' => 'Dọn các message bot gần đây',
            'resume' => 'Tiếp tục task đang bị chặn',
            'help' => 'Xem hướng dẫn điều khiển từ xa',
        ],
        'buttons' => [
            'code' => 'Code',
            'guide' => 'Hướng dẫn',
            'create_menu' => 'Tạo task',
            'reports_menu' => 'Báo cáo',
            'maintenance_menu' => 'Bảo trì',
            'back_home' => 'Về chính',
            'code_examples' => 'Ví dụ code',
            'task_templates' => 'Mẫu task',
            'template_bugfix' => 'Bugfix',
            'template_refactor' => 'Refactor',
            'template_review' => 'Mẫu review',
            'template_validate' => 'Mẫu validate',
            'latest_blocked' => 'Blocked mới nhất',
            'latest_failed' => 'Failed mới nhất',
            'latest_running' => 'Running mới nhất',
            'resume_latest_blocked' => 'Tiếp tục blocked mới nhất',
            'next_action' => 'Bước tiếp theo',
            'follow_up' => 'Follow-up',
            'validation' => 'Validation',
            'github' => 'GitHub',
            'cancel_task' => 'Hủy task',
            'cancel_latest_running' => 'Hủy running mới nhất',
            'cancel_all_active' => 'Hủy tất cả active',
            'delete_task' => 'Xóa queue',
            'delete_all_pending' => 'Xóa hết queue',
            'delete_all_tasks' => 'Xóa tất cả task',
            'latest_status' => 'Trạng thái mới nhất',
            'latest_summary' => 'Tóm tắt mới nhất',
            'latest_changes' => 'Thay đổi mới nhất',
            'latest_github' => 'GitHub mới nhất',
            'queue' => 'Hàng chờ',
            'chat_start' => 'Chat với Codex',
            'chat_status' => 'Trạng thái Chat',
            'chat_stop' => 'Thoát Codex',
            'chat_reset' => 'Reset Chat Mode',
            'clear_chat' => 'Dọn chat',
            'clear_all_chat' => 'Dọn tất cả chat',
            'reset' => 'Dọn chat',
            'status' => 'Trạng thái',
            'summary' => 'Tóm tắt',
            'changes' => 'Thay đổi',
            'review' => 'Chạy review',
            'validate' => 'Chạy validate',
            'pending' => 'Đang chờ',
            'running' => 'Đang chạy',
            'blocked' => 'Đang chặn',
            'failed' => 'Thất bại',
            'completed' => 'Hoàn thành',
            'cancelled' => 'Đã hủy',
            'resume' => 'Tiếp tục',
            'confirm_yes' => 'Đồng ý',
            'confirm_no' => 'Không',
        ],
        'labels' => [
            'clarify_request' => 'Làm rõ yêu cầu',
            'confirm_action' => 'Xác nhận hành động',
            'original_message' => 'Tin nhắn gốc',
            'action' => 'Hành động',
            'target' => 'Mục tiêu',
            'commands' => 'Các lệnh',
            'chat_session' => 'Chat session',
            'chat_mode' => 'Chat mode',
            'session_id' => 'Session id',
            'started_at' => 'Bắt đầu lúc',
            'last_message' => 'Tin nhắn cuối',
            'recent_activity' => 'Hoạt động gần đây',
            'activity_snapshot' => 'Tổng quan hoạt động',
            'needs_attention' => 'Cần chú ý',
            'current_tasks' => 'Task hiện tại',
            'task' => 'Task',
            'tasks' => 'Danh sách task',
            'summary' => 'Tóm tắt',
            'message' => 'Tin nhắn',
            'status' => 'Trạng thái',
            'repository' => 'Repository',
            'validation' => 'Validation',
            'validate' => 'Validation',
            'run' => 'Lần chạy',
            'machine' => 'Máy',
            'provider' => 'Provider',
            'phase' => 'Giai đoạn',
            'focus' => 'Đang tập trung',
            'worker' => 'Worker',
            'host' => 'Host',
            'issue' => 'Mã việc',
            'source_task' => 'Task nguồn',
            'next_action' => 'Bước tiếp theo',
            'follow_up' => 'Yêu cầu tiếp theo',
            'reason' => 'Lý do',
            'guidance' => 'Hướng dẫn',
            'workspace_policy' => 'Chính sách workspace',
            'input_type' => 'Loại đầu vào',
            'question' => 'câu hỏi',
            'total_commands' => 'Tổng số lệnh',
            'failed_commands' => 'Số lệnh lỗi',
            'branch' => 'Branch',
            'compare' => 'So sánh',
            'pull_request' => 'Pull request',
            'pr_note' => 'Ghi chú PR',
            'ci' => 'CI',
            'ci_note' => 'Ghi chú CI',
            'last_seen' => 'Lần cuối thấy',
            'configured' => 'Đã cấu hình',
            'url' => 'URL',
            'pending_updates' => 'Pending updates',
            'last_error' => 'Lỗi gần nhất',
            'scope' => 'Phạm vi',
            'deleted_tasks' => 'Task đã xóa',
            'changed_files' => 'Số file thay đổi',
            'failure' => 'Lỗi',
            'details' => 'Chi tiết',
            'headline' => 'Tóm tắt nhanh',
            'queued_task' => 'Task đã vào hàng chờ',
            'running_task' => 'Task đang chạy',
            'validation_for_task' => 'Validation của task',
            'github_for_task' => 'GitHub của task',
            'blockers' => 'Blocker',
            'bulk_cancellation_completed' => 'Hoàn tất hủy hàng loạt.',
            'deleted_pending_task' => 'Đã xóa hẳn task pending',
            'bulk_pending_deletion_completed' => 'Hoàn tất xóa hẳn hàng loạt task pending.',
            'changed_files_for_task' => 'File đã thay đổi của task',
            'resume_accepted_for_task' => 'Đã chấp nhận tiếp tục task',
            'workflow_steps' => 'Các bước workflow',
            'task_update' => 'Cập nhật task',
            'cancelled_immediately' => 'Đã hủy ngay',
            'cancellation_requested_running' => 'Đã yêu cầu hủy (running)',
            'unchanged' => 'Không đổi',
            'create_tasks' => 'Tạo task',
            'coding_task_examples' => 'Ví dụ task coding',
            'task_templates' => 'Mẫu task',
            'bugfix_template' => 'Mẫu bugfix',
            'refactor_template' => 'Mẫu refactor',
            'review_template' => 'Mẫu review',
            'validation_template' => 'Mẫu validation',
            'reports' => 'Báo cáo',
            'maintenance' => 'Bảo trì',
            'queue_management' => 'Quản lý hàng chờ',
            'recommended_next_actions' => 'Hành động gợi ý:',
            'example_prompts' => 'Ví dụ prompt:',
            'home_dashboard' => 'Tổng quan trang chủ',
            'quick_start' => 'Bắt đầu nhanh',
            'chat_session_started' => 'Đã bật chat session',
            'chat_session_stopped' => 'Đã tắt chat session',
            'chat_session_reset' => 'Đã reset chat session',
        ],
        'values' => [
            'yes' => 'có',
            'no' => 'không',
            'unknown' => 'không rõ',
            'online' => 'online',
            'stale' => 'stale',
            'pending' => 'đang chờ',
            'running' => 'đang chạy',
            'completed' => 'hoàn thành',
            'failed' => 'thất bại',
            'blocked' => 'đang chặn',
            'cancelled' => 'đã hủy',
            'skipped' => 'bỏ qua',
            'active' => 'active',
            'inactive' => 'inactive',
            'all' => 'all',
            'terminal' => 'terminal',
        ],
        'help' => [
            'title' => 'OPAS điều khiển coding từ xa',
            'no_worker_reported' => 'Chưa có worker nào báo về.',
            'quick_start_steps' => [
                '1. Dùng /start khi bạn muốn Telegram hoạt động như chat điều khiển Codex từ xa.',
                '2. Gửi tin nhắn bình thường; request sẽ vào hàng chờ của máy đang connected.',
                '3. Dùng /queue để xem, dừng, hoặc dọn việc đang chờ.',
                '4. Dùng /changes latest để xem file thay đổi, hoặc /clear khi xong phiên.',
            ],
            'commands' => [
                '/start - bật direct chat mode với Codex trên máy đang connected',
                '/chat_status - xem trạng thái chat session trực tiếp hiện tại',
                '/stop - tắt direct chat mode',
                '/chat_reset - xóa context chat hiện tại và bắt đầu lại sạch',
                '/changes [task-id|latest] - xem file thay đổi',
                '/queue [pending|running|blocked|failed|completed] - xem hàng chờ task',
                '/cancel [task-id|latest:running] - hủy một task',
                '/cancel_all - hủy toàn bộ việc active trong hàng chờ',
                '/delete [task-id|latest:pending] - xóa một task pending khỏi hàng chờ',
                '/delete_all - xóa toàn bộ task pending',
                '/clear [--force] - dọn message bot đã track trong phiên chat hiện tại',
                '/clear_all [--force] - dọn toàn bộ message bot đã track từ cũ đến mới',
            ],
            'buttons_hint' => 'Dùng các nút bên dưới cho chat mode, quản lý hàng chờ, file thay đổi, và dọn chat.',
            'no_active_tasks' => 'Hiện chưa có task auto-coding nào đang hoạt động.',
            'tip' => 'Gợi ý: nếu bạn mới dùng, hãy bắt đầu với /queue, sau đó /status latest, rồi /summary latest.',
        ],
        'menus' => [
            'create' => [
                'Dùng menu này khi bạn muốn bắt đầu task coding hoặc review từ xa.',
                'Các nút có thể chạy nhanh review và validation ngay lập tức.',
                'Với task coding, hãy gửi mô tả như: /code Refactor menu task Telegram',
                'Bạn có thể thêm chi tiết bằng các flag như --issue, --scope, --path, --provider, và --model.',
            ],
            'create_code' => [
                'Dùng /code khi bạn muốn máy đang kết nối triển khai hoặc refactor code.',
                'Flag hữu ích: --issue, --scope, --path, --provider, --model, --validate, --no-validate',
            ],
            'create_templates' => [
                'Dùng các mẫu này khi bạn muốn có điểm bắt đầu an toàn hơn là tự viết prompt từ đầu.',
                'Chọn mẫu bugfix, refactor, review, hoặc validation bên dưới rồi copy lệnh tương ứng.',
            ],
            'template_bugfix' => [
                'Dùng mẫu này khi có lỗi và bạn muốn máy tập trung vào phân tích, sửa lỗi, và verify.',
                'Thêm --scope nếu bạn đã biết file hoặc thư mục bị ảnh hưởng.',
            ],
            'template_refactor' => [
                'Dùng mẫu này khi hành vi cần giữ nguyên nhưng cấu trúc, độ rõ ràng, hoặc phần trùng lặp cần cải thiện.',
                'Nên dùng --scope hẹp cho refactor để máy giữ đúng boundary mong muốn.',
            ],
            'template_review' => [
                'Dùng mẫu này khi bạn muốn một lượt review tập trung vào lỗi, regression, và thiếu sót trong validation.',
                'Hãy kết hợp review với /summary latest hoặc /changes latest sau khi máy chạy xong.',
            ],
            'template_validate' => [
                'Dùng mẫu này khi bạn chủ yếu muốn chạy lint, static analysis, tests, hoặc các check đã cấu hình từ xa.',
                'Sau đó dùng /validation_report latest để xem kết quả ở dạng gọn.',
            ],
            'reports' => [
                'Dùng menu này để xem máy đang kết nối đã làm gì.',
                'Trạng thái mới nhất cho biết task mới nhất đang ở trạng thái nào.',
                'Tóm tắt mới nhất cho biết kết quả thực thi, validation, và bước tiếp theo.',
                'Thay đổi mới nhất liệt kê các file đã đổi của lần chạy gần nhất.',
                'GitHub hiển thị issue key hiện tại, repository slug, compare URL, và trạng thái PR hoặc CI nếu có.',
                'Hàng chờ cho biết các task gần đây đang chờ, chạy, bị chặn, lỗi, hoặc hoàn thành.',
                'Dùng bộ lọc Đang chờ, Đang chạy, Đang chặn, Thất bại, hoặc Hoàn thành khi bạn chỉ muốn xem một lát cắt workflow.',
            ],
            'maintenance' => [
                'Dùng menu này để dọn chat và điều hướng nhanh.',
                'Dọn chat sẽ xóa các message bot gần đây đã được theo dõi trong chat này.',
                'Hướng dẫn sẽ quay lại màn hình onboarding chính.',
                'Hàng chờ và Trạng thái mới nhất được đặt ở đây để dùng nhanh khi chat bị rối.',
                'Đồng bộ lệnh sẽ làm mới danh sách lệnh Telegram khi menu của bot thay đổi.',
                'Dùng các thao tác hủy để dừng một task hoặc toàn bộ task active trước khi tạo yêu cầu mới.',
                'Dùng purge khi bạn muốn xóa hẳn các task terminal cũ khỏi lịch sử.',
            ],
            'queue' => [
                'Dùng menu này để xem request đang chờ, đang chạy, hoặc đang bị chặn.',
                'Dừng task running mới nhất khi Codex đang xử lý sai yêu cầu.',
                'Xóa task pending khi một tin nhắn trong hàng chờ không còn cần nữa.',
            ],
        ],
        'phrases' => [
            'provide_value' => 'Hãy cung cấp một giá trị.',
            'no_next_action_recorded' => 'Hiện chưa có bước tiếp theo rõ ràng nào được ghi nhận.',
            'no_follow_up_required' => 'Hiện tại task này không yêu cầu follow-up nào.',
            'no_validation_run' => 'chưa có lần validation nào.',
            'no_recorded_changed_files' => 'chưa có file thay đổi nào được ghi nhận.',
            'more_files' => '+:count file khác',
            'no_execution_run' => 'chưa có lần thực thi nào.',
            'resume_workflow_continue' => 'Máy đang kết nối sẽ tiếp tục workflow này.',
            'task_removed_permanently' => 'Task đã bị xóa khỏi database vĩnh viễn.',
            'no_worker_machine_reported' => 'Chưa có worker auto-coding nào báo heartbeat.',
            'no_tasks_for_status_filter' => 'Không tìm thấy task auto-coding :status nào.',
            'no_local_tasks' => 'Không tìm thấy task auto-coding cục bộ nào.',
            'latest_tasks_for_status_filter' => 'Các task auto-coding :status mới nhất',
            'latest_tasks' => 'Các task auto-coding mới nhất',
            'task_without_changed_files' => 'Task #:task_id chưa có file thay đổi nào được ghi nhận.',
            'resume_format' => 'Mẫu tiếp tục: /resume :task_id :question_pairs',
            'chat_cleaned' => 'Đã dọn chat. Dùng /start hoặc các nút bên dưới để tiếp tục.',
            'chat_cleaned_force' => 'Đã dọn chat. Đã yêu cầu force cleanup; Telegram sẽ xóa thêm các message khác nếu bot có đủ quyền.',
            'chat_cleaned_all' => 'Đã dọn toàn bộ message bot đã track từ cũ đến mới. Dùng /start để tiếp tục.',
            'chat_cleaned_all_force' => 'Đã dọn toàn bộ message bot đã track từ cũ đến mới. Force cleanup cũng thử xóa message gọi lệnh nếu bot có quyền.',
            'changed_file_added' => 'Đã thêm trong lần chạy mới nhất.',
            'changed_file_deleted' => 'Đã xóa trong lần chạy mới nhất.',
            'changed_file_renamed' => 'Đã đổi tên hoặc di chuyển trong lần chạy mới nhất.',
            'changed_file_modified' => 'Đã chỉnh sửa trong lần chạy mới nhất.',
            'changed_file_touched' => 'Đã thay đổi trong lần chạy mới nhất; chưa có tóm tắt chi tiết theo file.',
            'chat_session_started' => 'Direct chat mode đã bật. Hãy gửi tin nhắn bình thường để Codex trả lời từ máy đang connected.',
            'chat_session_connected' => 'Đã kết nối Codex.',
            'chat_session_inactive' => 'Hiện direct chat mode đang tắt cho cuộc chat Telegram này.',
            'chat_session_start_hint' => 'Dùng /start khi bạn muốn tin nhắn Telegram hoạt động như một phiên Codex từ xa.',
            'chat_ping_received' => 'Bot Telegram đã nhận được tin nhắn của bạn.',
            'chat_ping_no_task_created' => 'Tin này được hiểu là kiểm tra kết nối nên không tạo task Codex. Khi muốn Codex xử lý, hãy gửi yêu cầu coding cụ thể.',
            'chat_session_reset' => 'Đã reset context direct chat. Tin nhắn tiếp theo sẽ bắt đầu một luồng coding từ xa mới.',
            'chat_session_stopped' => 'Direct chat mode đã tắt. Các slash command và báo cáo task vẫn dùng bình thường.',
            'chat_session_hint' => 'Khi chat mode đang bật, tin nhắn thường sẽ được Codex trả lời. Yêu cầu coding cụ thể vẫn tạo hàng chờ trên máy đang connected.',
            'direct_chat_queued' => 'Codex đang chuẩn bị trả lời...',
            'direct_chat_running' => 'Codex đang trả lời...',
            'direct_chat_failed' => 'Codex chưa trả lời được.',
            'direct_chat_empty' => 'Codex đã chạy xong nhưng không có nội dung trả lời.',
            'media_message_needs_caption' => 'Đã nhận ảnh. Hãy gửi lại ảnh kèm caption ngắn mô tả cần sửa, hoặc nhắn yêu cầu bằng text.',
            'chat_session_no_active_task' => 'Chat session này chưa gắn với task active nào.',
            'chat_session_no_recent_activity' => 'Hiện chưa có hoạt động chat session nào được ghi nhận.',
            'task_has_no_execution_run' => 'Task #:task_id chưa có lần thực thi nào.',
            'task_has_no_validation_run' => 'Task #:task_id chưa có lần validation nào.',
            'task_has_no_follow_up' => 'Task #:task_id hiện không yêu cầu follow-up.',
            'ci_failed_check_ratio' => ':failed/:total check đang lỗi',
            'validation_failed_command_ratio' => ':failed/:total lệnh validation đang lỗi',
            'github_headline_ci_attention' => 'CI đang cần xử lý trước khi merge.',
            'github_headline_pr_open_ci_passing' => 'PR đang mở và CI đang pass.',
            'github_headline_pr_closed' => 'Workflow pull request này đã đóng.',
            'github_headline_compare_ready' => 'Link compare của branch đã sẵn sàng để follow-up trên GitHub.',
            'github_headline_local_fallback' => 'GitHub context hiện chỉ có local fallback.',
            'github_blocker_compare_unavailable' => 'Hiện không có compare URL cho branch này.',
            'github_blocker_pr_unavailable' => 'Chưa lấy được trạng thái pull request; hãy kiểm tra GitHub thủ công hoặc cấu hình integration.',
            'github_blocker_ci_unavailable' => 'Hiện chưa đọc được trạng thái CI từ local GitHub context.',
            'github_blocker_ci_failed_default' => 'Các check CI hiện chưa pass.',
            'github_next_action_fix_ci' => 'Hãy xử lý các check CI đang lỗi trước khi merge.',
            'github_next_action_open_compare_pr' => 'Mở compare URL để tạo hoặc kiểm tra pull request.',
            'github_next_action_review_merge_pr' => 'Review pull request hiện tại và merge khi sẵn sàng.',
            'github_next_action_no_follow_up' => 'Hiện chưa cần follow-up GitHub thêm.',
            'github_next_action_manual_follow_up' => 'Hãy xem compare URL và tiếp tục follow-up GitHub thủ công.',
            'queued_reused_issue_context' => 'Đã tái dùng issue context từ task #:task_id.',
            'queued_scope_path_count' => ':count đường dẫn',
            'cancel_requested' => 'Đã gửi yêu cầu hủy. Worker sẽ dừng lần chạy này ở checkpoint an toàn kế tiếp.',
            'cancelled_removed_from_active' => 'Task đã được hủy và gỡ khỏi luồng thực thi active.',
            'pending_interaction_cancelled' => 'Đã hủy xác nhận đang chờ.',
            'workflow_step_inspect_repository' => 'Kiểm tra repository',
            'workflow_step_prepare_prompt' => 'Chuẩn bị prompt',
            'workflow_step_provider_plan' => 'Thực thi với provider',
            'workflow_step_collect_github_context' => 'Thu thập GitHub context',
            'workflow_step_run_validation' => 'Chạy validation',
            'workflow_step_completion_check' => 'Kiểm tra hoàn tất',
            'workflow_phase_execution_started' => 'Đã bắt đầu thực thi',
            'workflow_focus_execution_started' => 'Máy đang connected đã nhận task và bắt đầu chạy workflow từ xa.',
            'workflow_focus_in_progress' => 'Máy đang connected vẫn đang xử lý giai đoạn hiện tại.',
            'workflow_focus_blocked' => 'Workflow đang chờ operator phản hồi trước khi tiếp tục.',
            'workflow_focus_completed' => 'Giai đoạn workflow mới nhất đã hoàn tất.',
            'workflow_focus_failure' => 'Workflow đã dừng vì một giai đoạn thực thi bị lỗi.',
            'chat_timeline_queued' => 'Đã đưa task #:task_id vào hàng chờ.',
            'chat_timeline_running' => 'Task #:task_id đang chạy.',
            'chat_timeline_completed' => 'Task #:task_id đã hoàn thành.',
            'chat_timeline_failed' => 'Task #:task_id bị lỗi.',
            'chat_timeline_blocked' => 'Task #:task_id đang bị chặn.',
            'chat_timeline_cancelled' => 'Task #:task_id đã bị hủy.',
            'clarify_request_prompt' => 'Tin nhắn của bạn còn mơ hồ. Hãy chọn việc bạn muốn bot làm tiếp.',
            'issue_context_clarify_prompt' => 'Tôi tìm thấy nhiều context :task_type trước đó cho issue :issue_key. Hãy chọn context cần tái dùng.',
            'issue_context_reply_hint' => 'Hãy trả lời bằng source task id hoặc chọn một nút bên dưới.',
            'confirm_action_prompt' => 'Hãy xác nhận hành động này trước khi chạy thật.',
            'no_pending_clarification' => 'Hiện không có yêu cầu làm rõ nào đang chờ. Hãy gửi lại yêu cầu.',
            'no_pending_issue_context_clarification' => 'Hiện không có lựa chọn issue context nào đang chờ. Hãy gửi lại yêu cầu.',
            'no_pending_confirmation' => 'Hiện không có xác nhận nào đang chờ. Hãy gửi lại lệnh.',
        ],
    ],
];
