server {
    listen 8882;
    server_name localhost;

    location / {
        set $n8n_upstream http://n8n:5678;
        proxy_pass $n8n_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
