server {
    listen 8885;

    location / {
        set $python_upstream http://python-services:5000;
        proxy_pass $python_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
