<?php

declare(strict_types=1);

namespace Tests\Feature\Controllers\Api;

use App\Enums\UserRole;
use App\Models\AuthProvider;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Log;
use Tests\TestCase;

/**
 * Verify the admin-facing auth provider management API.
 */
class AdminAuthProviderApiControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Admins should see the full provider list used by the configuration UI.
     */
    public function test_admin_can_list_auth_providers(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->getJson(route('api.admin.auth.providers.index'));

        $response->assertOk()
            ->assertJsonCount(4, 'data')
            ->assertJsonPath('data.0.key', 'email');
    }

    /**
     * OAuth providers should expose callback URLs generated by backend routes instead of frontend guesses.
     */
    public function test_admin_listing_includes_backend_generated_callback_url_for_oauth_providers(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->getJson(route('api.admin.auth.providers.index'));

        $response->assertOk()
            ->assertJsonPath(
                'data.1.metadata.callback_url',
                route('api.auth.providers.callback', ['key' => 'google']),
            );
    }

    /**
     * Non-admin users must not access the admin provider listing endpoint.
     */
    public function test_non_admin_cannot_list_auth_providers(): void
    {
        $member = User::factory()->create([
            'role' => UserRole::Member,
        ]);

        $response = $this
            ->actingAs($member)
            ->getJson(route('api.admin.auth.providers.index'));

        $response->assertForbidden();
    }

    /**
     * Non-admin users must not update provider settings from the admin endpoint.
     */
    public function test_non_admin_cannot_update_auth_provider(): void
    {
        $member = User::factory()->create([
            'role' => UserRole::Member,
        ]);

        $response = $this
            ->actingAs($member)
            ->putJson(route('api.admin.auth.providers.update', ['key' => 'google']), [
                'enabled' => true,
            ]);

        $response->assertForbidden();
    }

    /**
     * Guests must authenticate before accessing admin provider settings.
     */
    public function test_guest_cannot_list_auth_providers(): void
    {
        $response = $this->getJson(route('api.admin.auth.providers.index'));

        $response->assertUnauthorized();
    }

    /**
     * Guests must authenticate before updating admin provider settings.
     */
    public function test_guest_cannot_update_auth_provider(): void
    {
        $response = $this->putJson(route('api.admin.auth.providers.update', ['key' => 'google']), [
            'enabled' => true,
        ]);

        $response->assertUnauthorized();
    }

    /**
     * Admin-only provider endpoints should also send no-store headers because they expose sensitive config metadata.
     */
    public function test_admin_provider_listing_is_not_cacheable(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->getJson(route('api.admin.auth.providers.index'));

        $cacheControl = (string) $response->headers->get('Cache-Control', '');

        $response->assertOk()
            ->assertHeader('Pragma', 'no-cache');

        $this->assertStringContainsString('no-store', $cacheControl);
        $this->assertStringContainsString('no-cache', $cacheControl);
        $this->assertStringContainsString('must-revalidate', $cacheControl);
    }

    /**
     * Secrets are persisted but never returned in plain text from the response payload.
     */
    public function test_admin_can_update_provider_without_exposing_secrets(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->putJson(route('api.admin.auth.providers.update', ['key' => 'google']), [
                'enabled' => true,
                'visibility' => 'public',
                'public_config' => [
                    'client_id' => 'google-client-id',
                    'redirect_uri' => 'https://example.com/auth/google/callback',
                    'button_text' => 'Continue with Google',
                ],
                'secret_config' => [
                    'client_secret' => 'google-secret',
                ],
            ]);

        $response->assertOk()
            ->assertJsonPath('data.key', 'google')
            ->assertJsonPath('data.ready', true)
            ->assertJsonPath('data.active', true)
            ->assertJsonPath('data.secret_status.client_secret', true)
            ->assertJsonMissingPath('data.secret_config');

        $provider = AuthProvider::query()->where('key', 'google')->firstOrFail();

        $this->assertSame('google-secret', $provider->secret_config['client_secret']);
    }

    /**
     * Successful provider updates should emit a structured audit entry without leaking secret values.
     */
    public function test_admin_update_logs_auditable_provider_changes_without_secret_values(): void
    {
        Log::spy();

        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->putJson(route('api.admin.auth.providers.update', ['key' => 'google']), [
                'enabled' => true,
                'visibility' => 'public',
                'public_config' => [
                    'client_id' => 'google-client-id',
                    'redirect_uri' => 'https://example.com/auth/google/callback',
                ],
                'secret_config' => [
                    'client_secret' => 'google-secret',
                ],
            ]);

        $response->assertOk();

        Log::shouldHaveReceived('info')
            ->once()
            ->withArgs(function (string $message, array $context) use ($admin): bool {
                $encodedContext = json_encode($context);

                return $message === 'security.auth_provider_settings_updated'
                    && $context['actor_user_id'] === $admin->id
                    && $context['provider_key'] === 'google'
                    && in_array('client_id', $context['changed_public_config_keys'], true)
                    && in_array('redirect_uri', $context['changed_public_config_keys'], true)
                    && in_array('client_secret', $context['changed_secret_config_keys'], true)
                    && array_key_exists('enabled', $context['changed_attributes'])
                    && is_string($encodedContext)
                    && ! str_contains($encodedContext, 'google-secret');
            });
    }

    /**
     * Email provider updates must persist the locked required verification policy.
     */
    public function test_admin_email_provider_update_forces_required_email_verification_mode(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->putJson(route('api.admin.auth.providers.update', ['key' => 'email']), [
                'enabled' => true,
                'display_name' => 'Email and Password',
                'sort_order' => 10,
                'visibility' => 'public',
                'email_verification_mode' => 'required',
            ]);

        $response->assertOk()
            ->assertJsonPath('data.key', 'email')
            ->assertJsonPath('data.email_verification_mode', 'required');

        $this->assertDatabaseHas('auth_providers', [
            'key' => 'email',
            'email_verification_mode' => 'required',
        ]);
    }

    /**
     * Unknown provider keys must return a not found response instead of mutating unrelated state.
     */
    public function test_admin_update_returns_not_found_for_unknown_provider(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->putJson(route('api.admin.auth.providers.update', ['key' => 'unknown-provider']), [
                'enabled' => true,
            ]);

        $response->assertNotFound();
    }

    /**
     * Enabling an OAuth provider without its required configuration must be rejected.
     */
    public function test_admin_update_rejects_enabling_provider_without_required_config(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->putJson(route('api.admin.auth.providers.update', ['key' => 'google']), [
                'enabled' => true,
                'visibility' => 'public',
                'public_config' => [
                    'client_id' => 'google-client-id',
                ],
                'secret_config' => [],
            ]);

        $response->assertUnprocessable()
            ->assertJsonValidationErrors([
                'public_config.redirect_uri',
                'secret_config.client_secret',
            ]);
    }

    /**
     * Provider updates should reject unexpected nested config keys instead of storing free-form payloads.
     */
    public function test_admin_update_rejects_unexpected_nested_provider_config_keys(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->putJson(route('api.admin.auth.providers.update', ['key' => 'google']), [
                'capabilities' => [
                    'login' => true,
                    'unexpected' => true,
                ],
                'public_config' => [
                    'client_id' => 'google-client-id',
                    'unexpected' => 'value',
                ],
                'secret_config' => [
                    'client_secret' => 'google-secret',
                    'unexpected' => 'value',
                ],
            ]);

        $response->assertUnprocessable()
            ->assertJsonValidationErrors([
                'capabilities',
                'public_config',
                'secret_config',
            ]);
    }

    /**
     * Email provider updates must reject verification policies weaker than required.
     */
    public function test_admin_update_rejects_non_required_email_verification_mode_for_email_provider(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->putJson(route('api.admin.auth.providers.update', ['key' => 'email']), [
                'email_verification_mode' => 'disabled',
            ]);

        $response->assertUnprocessable()
            ->assertJsonValidationErrors(['email_verification_mode']);
    }

    /**
     * The final working login path must remain available to avoid locking administrators out.
     */
    public function test_admin_cannot_disable_last_active_login_provider(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        AuthProvider::query()->where('key', 'google')->update(['enabled' => false]);
        AuthProvider::query()->where('key', 'facebook')->update(['enabled' => false]);
        AuthProvider::query()->where('key', 'github')->update(['enabled' => false]);

        $response = $this
            ->actingAs($admin)
            ->putJson(route('api.admin.auth.providers.update', ['key' => 'email']), [
                'enabled' => false,
                'display_name' => 'Email',
                'sort_order' => 10,
                'visibility' => 'public',
            ]);

        $response->assertUnprocessable()
            ->assertJsonValidationErrors(['enabled']);
    }

    /**
     * The final working login path must stay usable even if a client submits capability changes directly.
     */
    public function test_admin_cannot_disable_last_active_login_capability(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        AuthProvider::query()->where('key', 'google')->update(['enabled' => false]);
        AuthProvider::query()->where('key', 'facebook')->update(['enabled' => false]);
        AuthProvider::query()->where('key', 'github')->update(['enabled' => false]);

        $response = $this
            ->actingAs($admin)
            ->putJson(route('api.admin.auth.providers.update', ['key' => 'email']), [
                'enabled' => true,
                'capabilities' => [
                    'login' => false,
                    'register' => true,
                    'link_account' => false,
                    'requires_redirect' => false,
                    'supports_email_verification' => true,
                    'supports_password' => true,
                ],
            ]);

        $response->assertUnprocessable()
            ->assertJsonValidationErrors(['capabilities.login']);
    }
}
