<?php

declare(strict_types=1);

namespace Tests\Feature\Controllers\Api;

use App\Enums\UserRole;
use App\Models\AuthProvider;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * Verify the admin-facing auth provider management API.
 */
class AdminAuthProviderApiControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Admins should see the full provider list used by the configuration UI.
     */
    public function test_admin_can_list_auth_providers(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->getJson(route('api.admin.auth.providers.index'));

        $response->assertOk()
            ->assertJsonCount(4, 'data')
            ->assertJsonPath('data.0.key', 'email');
    }

    /**
     * OAuth providers should expose callback URLs generated by backend routes instead of frontend guesses.
     */
    public function test_admin_listing_includes_backend_generated_callback_url_for_oauth_providers(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->getJson(route('api.admin.auth.providers.index'));

        $response->assertOk()
            ->assertJsonPath(
                'data.1.metadata.callback_url',
                route('api.auth.providers.callback', ['key' => 'google']),
            );
    }

    /**
     * Non-admin users must not access the admin provider listing endpoint.
     */
    public function test_non_admin_cannot_list_auth_providers(): void
    {
        $member = User::factory()->create([
            'role' => UserRole::Member,
        ]);

        $response = $this
            ->actingAs($member)
            ->getJson(route('api.admin.auth.providers.index'));

        $response->assertForbidden();
    }

    /**
     * Admin-only provider endpoints should also send no-store headers because they expose sensitive config metadata.
     */
    public function test_admin_provider_listing_is_not_cacheable(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->getJson(route('api.admin.auth.providers.index'));

        $cacheControl = (string) $response->headers->get('Cache-Control', '');

        $response->assertOk()
            ->assertHeader('Pragma', 'no-cache');

        $this->assertStringContainsString('no-store', $cacheControl);
        $this->assertStringContainsString('no-cache', $cacheControl);
        $this->assertStringContainsString('must-revalidate', $cacheControl);
    }

    /**
     * Secrets are persisted but never returned in plain text from the response payload.
     */
    public function test_admin_can_update_provider_without_exposing_secrets(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        $response = $this
            ->actingAs($admin)
            ->putJson(route('api.admin.auth.providers.update', ['key' => 'google']), [
                'enabled' => true,
                'visibility' => 'public',
                'public_config' => [
                    'client_id' => 'google-client-id',
                    'redirect_uri' => 'https://example.com/auth/google/callback',
                    'button_text' => 'Continue with Google',
                ],
                'secret_config' => [
                    'client_secret' => 'google-secret',
                ],
            ]);

        $response->assertOk()
            ->assertJsonPath('data.key', 'google')
            ->assertJsonPath('data.ready', true)
            ->assertJsonPath('data.active', true)
            ->assertJsonPath('data.secret_status.client_secret', true)
            ->assertJsonMissingPath('data.secret_config');

        $provider = AuthProvider::query()->where('key', 'google')->firstOrFail();

        $this->assertSame('google-secret', $provider->secret_config['client_secret']);
    }

    /**
     * The final working login path must remain available to avoid locking administrators out.
     */
    public function test_admin_cannot_disable_last_active_login_provider(): void
    {
        $admin = User::factory()->create([
            'role' => UserRole::Admin,
        ]);

        AuthProvider::query()->where('key', 'google')->update(['enabled' => false]);
        AuthProvider::query()->where('key', 'facebook')->update(['enabled' => false]);
        AuthProvider::query()->where('key', 'github')->update(['enabled' => false]);

        $response = $this
            ->actingAs($admin)
            ->putJson(route('api.admin.auth.providers.update', ['key' => 'email']), [
                'enabled' => false,
                'display_name' => 'Email',
                'sort_order' => 10,
                'visibility' => 'public',
            ]);

        $response->assertUnprocessable()
            ->assertJsonValidationErrors(['enabled']);
    }
}
